CREATE TABLE PLANETA (
    ID NUMERIC(18,2) NOT NULL PRIMARY KEY,
    NOME VARCHAR(60) NOT NULL,
    CLIMA VARCHAR(60) NOT NULL,
    TERRENO VARCHAR(60) NOT NULL,
    APARICOESEMFILMES NUMERIC(18,2)
);

CREATE SEQUENCE IDPLANETA START WITH 1 INCREMENT BY 1;